apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-creds
data:
  credentials: |
    [jlerocher]
    aws_access_key_id = AKIA4SKFF73SSCS6ERAD
    aws_secret_access_key = 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