apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  labels:
    app: user
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
      - name: user
        image: jlerocher/udagram-api-user:v1
        ports:
        - containerPort: 8080
        envFrom:
          - configMapRef:
              name: env-configmap
          - secretRef:
              name: env-pg-secrets
        volumeMounts:
          - mountPath: "/root/aws"
            name: aws-creds
      volumes:
        - name: aws-creds
          configMap:
            name: aws-creds
