name: Build and push images

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - run: docker-compose -f docker-compose-build.yaml build --parallel
    - run: docker tag udagram-api-user jlerocher/udagram-api-user
    - run: docker tag udagram-api-feed jlerocher/udagram-api-feed
    - run: docker tag udagram-frontend jlerocher/udagram-frontend
    - run: docker tag reverseproxy jlerocher/udagram-reverseproxy
    - run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    - run: docker push udagram-reverseproxy
    - run: docker push udagram-frontend
    - run: docker push udagram-api-user
    - run: docker push udagram-api-feed